# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='cost_per_day',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
