# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_room_cost_per_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='f_promotion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='f_recommendation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='feature1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='room',
            name='feature2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='room',
            name='feature3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.CharField(choices=[('SG', 'Single Room'), ('DB', 'Double Room'), ('TW', 'Twin Room'), ('ST', 'Suite Room'), ('DX', 'Deluxe Room'), ('PR', 'Premier Room'), ('FM', 'Family Room')], max_length=2),
        ),
    ]
