# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 13:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_auto_20170522_0344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='cost_per_day',
            new_name='cost_per_night',
        ),
    ]
