# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_auto_20170522_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(upload_to='image_upload'),
        ),
    ]
