# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 18:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0002_room_cost_per_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('n_room', models.PositiveSmallIntegerField()),
                ('n_adult', models.PositiveSmallIntegerField()),
                ('n_child', models.PositiveSmallIntegerField()),
                ('coupon', models.BooleanField()),
                ('discount', models.PositiveSmallIntegerField()),
                ('n_breakfase', models.PositiveSmallIntegerField()),
                ('n_babybed', models.PositiveSmallIntegerField()),
                ('addendum', models.TextField()),
                ('card_type', models.CharField(choices=[('VS', 'Visa'), ('MS', 'Master'), ('AE', 'American Express'), ('DC', 'Discover')], max_length=2)),
                ('card_number', models.CharField(max_length=16)),
                ('cvc', models.CharField(max_length=3)),
                ('expiration_month', models.CharField(max_length=2)),
                ('expiration_year', models.CharField(max_length=4)),
                ('send_receipt', models.CharField(blank=True, choices=[('C', 'Cell Phone'), ('E', 'E-mail')], max_length=1)),
                ('reserved_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_accounts_user', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.Room')),
                ('staff', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_accounts_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
