# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('discount', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='discount',
            new_name='n_baby_bed',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='n_babybed',
            new_name='n_breakfast',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='n_breakfase',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='coupon',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='reservations.Coupon'),
        ),
    ]
