# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 08:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_auto_20170522_2313'),
        ('reservations', '0002_auto_20170522_2257'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomReservationInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_room', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='cvc',
            new_name='card_cvc',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='expiration_month',
            new_name='card_expire_month',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='expiration_year',
            new_name='card_expire_year',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='n_room',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='room',
        ),
        migrations.AddField(
            model_name='reservation',
            name='modified_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservations.Coupon'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='send_receipt',
            field=models.CharField(blank=True, choices=[('C', 'Cell Phone'), ('E', 'E-mail')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_accounts_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roomreservationinfo',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.Reservation'),
        ),
        migrations.AddField(
            model_name='roomreservationinfo',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.Room'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='rooms',
            field=models.ManyToManyField(through='reservations.RoomReservationInfo', to='rooms.Room'),
        ),
    ]
