# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_auto_20170527_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='addendum',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='card_type',
            field=models.CharField(choices=[('VS', 'Visa'), ('AE', 'American Express'), ('DC', 'Discover')], max_length=2),
        ),
    ]
