# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 18:33
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_auto_20170528_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='send_receipt',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('C', 'Cell Phone'), ('E', 'E-mail')], max_length=3, null=True),
        ),
    ]
