# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_auto_20170529_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='total_cost',
            field=models.PositiveIntegerField(default=1024.11),
            preserve_default=False,
        ),
    ]
