# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 15:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20170603_0006'),
        ('reservations', '0007_reservation_total_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='memberships.Coupon'),
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
