# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_auto_20170528_2005'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='coupons',
            field=models.ManyToManyField(to='reservations.Coupon'),
        ),
    ]
