# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 08:07
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_coupons'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.TextField(default='010-0101-0101', validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '010-1010-1010'. Up to 11 digits allowed.", regex='^\\d{3}-\\d{3,4}-\\d{4}$')]),
            preserve_default=False,
        ),
    ]
