# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='coupons',
            field=models.ManyToManyField(blank=True, to='reservations.Coupon'),
        ),
    ]
